//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectsTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveProject
    {
        public int IDActive { get; set; }
        public int IDPerson { get; set; }
        public int IDProject { get; set; }
        public int Percentage { get; set; }
        public System.DateTime StartActiveDate { get; set; }
        public System.DateTime EndActiveDate { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Project Project { get; set; }
    }
}
